#ifndef __MERCKU_CONSTANTS_H__
#define __MERCKU_CONSTANTS_H__

/// version of mercku_os.
#define SDK_VERSION "1.0.0"
/// 这个 SDK 的编译目标，用于定制。
#define SDK_TARGET_THREAD "mercku"

#define MERCKU_SN_LEN 15

#define MERCKU_NAME_LEN 64
#define MERCKU_HOST_LEN 64
#define MERCKU_HOST_MAX 64 // 最多支持的 url filter 规则数量

#define MERCKU_USER_LEN 64
#define MERCKU_PASSWORD_LEN 64
#define MERCKU_DOMAIN_LEN 64
#define MERCKU_URL_LEN 1024

#define MERCKU_MAC_LEN 18 // 00:11:22:33:44:55

#define MERCKU_IP_LEN 18   // INET_ADDRSTRLEN
#define MERCKU_IPV6_LEN 45 // INET6_ADDRSTRLEN

#define MERCKU_USERINFO_USERNAME_ROOT "root"
#define MERCKU_USERINFO_USERNAME_ADMIN "admin"

#define MERCKU_BLACKLIST_MAX 30

#define MERCKU_MAX_FILE_PATH_LEN 256

#define MERCKU_VPN_ITEM_MAX 5
#define MERCKU_VPN_NAME_LEN MERCKU_NAME_LEN // 32
#define MERCKU_VPN_PROTOCOL_LEN 16
#define MERCKU_VPN_USERNAME_LEN MERCKU_USER_LEN     // 64
#define MERCKU_VPN_PASSWORD_LEN MERCKU_PASSWORD_LEN // 64
#define MERCKU_VPN_SERVER_LEN MERCKU_DOMAIN_LEN     // 64

#define MERCKU_VPN_ERROR_MSG_LEN 64
#define MERCKU_VPN_ERROR_CODE_LEN 8
#define MERCKU_VPN_CONNECT_STAT_LEN 16

#define MERCKU_DNS_NUM 6
#define MERCKU_MASK_LEN MERCKU_IP_LEN
#define MERCKU_SSID_LEN 32
#define MERCKU_WIFI_KEY_LEN 128
#define MERCKU_MAX_PSK_LEN 64
#define MERCKU_MAX_TX_POWER 8

#endif // __MERCKU_CONSTANTS_H__